# Generated by Django 3.2.8 on 2021-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balancesheet',
            old_name='stockName',
            new_name='name',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
