NIFTY50 = ["VEDL", "BHARTIARTL", "ZEEL", "TECHM", "SUNPHARMA", "WIPRO", "CIPLA", "HCLTECH", "POWERGRID", "TCS", "RELIANCE", "BPCL", 
"INFRATEL", "ITC", "HEROMOTOCO", "MARUTI", "GRASIM", "BAJAJ-AUTO", "UPL", "DRREDDY", "TATASTEEL", "GAIL", "INFY", "HINDALCO", "NTPC", 
"ADANIPORTS", "TATAMOTORS", "HINDUNILVR", "SBIN", "JSWSTEEL", "COALINDIA", "SHREECEM", "NESTLEIND", "TITAN", "EICHERMOT", "BRITANNIA", 
"ONGC", "M&M", "IOC", "ULTRACEMCO", "BAJAJFINSV", "ICICIBANK", "HDFCBANK", "LT", "AXISBANK", "KOTAKBANK", "INDUSINDBK", 
"HDFC", "BAJFINANCE", "ASIANPAINT"]